### ISSUE TITLE
Use Official Safari Extension if possible 

### ISSUE THREAD

**Issue by lukmdo** [arthurhammer/github-toc#14]
It would be much better (could get easier/secure for users) to get it as official safari extension (same as its done for ff and chrome now).

See
https://safari-extensions.apple.com/?q=GitHub

This potentially relastes relates to 
#10

**Comment by arthurhammer** [comment]
Absolutely, I realise the state of the Safari version is very unfortunate. Without a certificate we can't build the extension at all, not even to publish as a standalone extension outside the Apple Extensions Gallery.

My plan is to enter the Apple Developer Program within the month. Then I can finally bring the Safari version up to date.
