### ISSUE TITLE
Add support for other URLs

### ISSUE THREAD

**Issue by awrichar** [arthurhammer/github-toc#16]
Thanks for the useful extension! Would be even more useful if I could apply it when browsing GitHub Enterprise sites. I can manually unpack the plugin and add URLs to the Chrome config, but if this could be a native setting, it would be great.

**Comment by fregante** [comment]
I recently published 2 modules that might help you with this:


https://github.com/fregante/webext-domain-permission-toggle
https://github.com/fregante/webext-dynamic-content-scripts

You'd just need:


```sh
npm i webext-domain-permission-toggle webext-dynamic-content-scripts
```

```js
// in background.js
import 'webext-dynamic-content-scripts';
import addDomainPermissionToggle from 'webext-domain-permission-toggle';

addDomainPermissionToggle();
```

And [some adjustments to manifest.json](https://github.com/fregante/webext-dynamic-content-scripts/blob/master/how-to-add-github-enterprise-support-to-web-extensions.md)
