### ISSUE TITLE
Attaches to sidebar instead of main content on wikis with custom sidebar

### ISSUE THREAD

**Issue by arthurhammer** [arthurhammer/github-toc#2]
Example: https://github.com/mbostock/d3/wiki

<img width="500" alt="screenshot - 2016-03-23 22 57 39" src="https://cloud.githubusercontent.com/assets/4521216/14019415/f37cd2ac-f1d2-11e5-8618-019b9cda55c6.png">

**Comment by aensley** [comment]
I am currently experiencing this same issue. I was about to open a new issue thinking it was related to private vs. public wiki pages, but sure enough, it's because I have a custom sidebar.

Chrome Version: 50.0.2661.102 (64-bit)
Plugin version: 0.2.3

**Comment by arthurhammer** [comment]
Thanks for your feedback. I'll issue a new release with the fix soon!

**Comment by aensley** [comment]
I may submit a pull request to fix this since your plugin is _exactly_ what my team needs, and there's nothing else like it. Do you have any rules for contributing? I couldn't find any with a quick search.

**Comment by arthurhammer** [comment]
Andrew, sorry for getting back to you this late. I released the new version with the fix in place. v0.2.4 should appear in the Chrome Store soon.

Contributions are welcome! No specific rules so far, I might add a Contributing.md later.

**Comment by aensley** [comment]
I got the update, and it works perfectly! Thank you!
