### ISSUE TITLE
Support for toc on issues page

### ISSUE THREAD

**Issue by HaveF** [arthurhammer/github-toc#4]
# Feature request?

Could it be a good idea to support the ToC on issues page?
# Reason

Because some love to write something on issue page, of course, on the first block of issue page
# And

If it support on gists, there is no reason to not support on issue page

:blush: thanks for your plugin, do love it

**Comment by arthurhammer** [comment]
Sorry to get back to you this late. Thanks for your feedback! 

I have considered adding it to issue pages before, just didn't think people would write this much in there. 😄. I will work on this soon.
